apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  env: dev

resources:
  - ../../base/

configMapGenerator:
  - name: application-configmap
    behavior: merge
    literals:
      - INFO_APP_ENV=dev