apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  env: int

resources:
  - ../../base/

patchesStrategicMerge:
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: application-configmap
    behavior: merge
    literals:
      - INFO_APP_ENV=int