apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-bizdevops
  labels:
    app: agentic-bizdevops
    type: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-bizdevops
  template:
    metadata:
      labels:
        app: agentic-bizdevops
    spec:
      containers:
      - name: agentic-bizdevops
        image: agentic-bizdevops
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "2"
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - configMapRef:
              name: application-configmap