apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: agentic-bizdevops
  framework: quarkus

buildMetadata: [managedByLabel]

resources:
  - microservice-deployment.yaml
  - microservice-service.yaml

configMapGenerator:
  - name: application-configmap
    literals:
      - INFO_DEVELOPER=lreimer